### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by ankmanu** [chatcannon/galvani#14]
I'm new to python, how do I run the code? Where to put the .mpt-File (from a BioLogic device) to translate? Thanks in advance!

**Comment by chatcannon** [comment]
Sorry for taking so long to reply. I'm going to have a go at packaging the code on PyPI (issue #7) and after that it should be easier.

**Comment by chatcannon** [comment]
OK, so now you should be able to install galvani with `pip install galvani`. Next up you can run, inside Python:
```python
from galvani import BioLogic

mpt_array, comments = BioLogic.MPTfile('path/to/mpt/file.mpt')
```

**Comment by ankmanu** [comment]
Thanks a lot!
