### ISSUE TITLE
TypeError when using numpy 1.12.0

### ISSUE THREAD

**Issue by ticino** [chatcannon/galvani#4]
Hi,

get a TypeError when using galvani with numpy v1.12.0.

<pre>
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    mpt1, comments = MPRfile(os.path.join(testdata_dir, 'test.mpr'))
  File "/usr/local/lib/python3.5/dist-packages/galvani-0.0.1a1-py3.5.egg/galvani/BioLogic.py", line 298, in __init__
TypeError: only integer scalar arrays can be converted to a scalar index
</pre>

**Comment by chatcannon** [comment]
Hi, @ticino, thanks for reporting this. I recently moved to a new city and I don't have internet at home yet, I have to do everything from internet cafes. So it will be a couple of weeks before I get around to fixing this. I just thought I should let you know so you don't think your message has gone to /dev/null
